# 第2章 NumPy基础

2017-07-20 王斌 python3

本章涵盖以下内
 数据类型；
 数组类型；
 类型转换；
 创建数组；
 数组索引；
 数组切片；
 改变维度。

**创建数组**

import numpy as np

np.array([])                #由列表生成数组

np.arange(n)                #生成序列数组

np.arange(n,dtype=np.类型)  #生成序列数组，定义类型

np.sctypeDict               #完整的NumPy数据类型列表

np.array([1,2+1.j,3.j + 1]) #复数表达





**使用数组**

a[m,n,l]                  #选取数组元素

a[:,0:1,-1]               #切片操作

a.tolist()                #将NumPy数组转换成Python列表

a.copy()                  #数组的复制

a.astype(str)             #将元素类型转换为指定数据类型,view





**数组变换**

a.ravel()                 #拉伸为一维操作，view

a.flatten()               #拉伸为一维操作

a.reshape(m,n,l)          #重定义数组尺寸，view,有-1操作

a.shape=(m,n,l)           #重定义数组尺寸,有-1操作

a.resize(m,n,l)           #重定义数组尺寸

a.transpose()             #转置矩阵

a.T                       #转置矩阵,view





**数组的组合**

np.hstack((a,b))      #水平组合 = column_stack

np.vstack((a,b))      #垂直组合 = row_stack

np.dstack((a,b))      #深度组合





**数组的分割**

np.hsplit(c,m)        #水平分割 ,hstack的逆向操作

np.vsplit(c,m)        #垂直分割 ,vstack的逆向操作

np.dsplit(c,m)        #深度分割 ,dstack的逆向操作





**数组的属性**

a.ndim                #给出数组的维数，或数组轴的个数

a.size                #给出数组元素的总个数

a.itemsize            #元素在内存中所占的字节数

a.dtype               #数据类型

a.nbytes              #整个数组所占的存储空间

a.shape               #数组尺寸

a.real                #给出复数数组的实部

a.imag                #给出复数数组的虚部

a.flat                #返回numpy.flatiter对象，用于for和切片

a.flat = 0            #对flat属性赋值将导致整个数组的元素都被覆盖



In [1]:
from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = "all"

## 2.1 Numpy数组对象

In [2]:
import numpy as np
a = np.arange(5)
a.dtype
a
a.shape

dtype('int32')

array([0, 1, 2, 3, 4])

(5,)

## 2.2 创建多维数组

array函数可以依据给定的对象生成数组。给定的对象应是类数组，如Python中的列表。

In [3]:
m=np.array([ np.arange(2),np.arange(2)])
m
m.shape

array([[0, 1],
       [0, 1]])

(2, 2)

In [4]:
m=np.array([ np.arange(3),np.arange(3),np.arange(3)])
m
m.shape

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

(3, 3)

In [5]:
a=np.arange(24).reshape(2,3,4)
a
a.shape
[[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]]
np.array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(2, 3, 4)

[[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]],
 [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### 2.2.1选取数组元素

在创建这个多维数组时，我们给array函数传递的对象是一个嵌套的列表。现在来依次选取
该数组中的元素。

In [6]:
a
a[1]
a[1,1]
a[1,1,1]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

array([16, 17, 18, 19])

17

### 2.2.2Numpy数据类型

以下是原书中的数据类型,原书是python2版本.

bool 									用一位存储的布尔类型（值为TRUE或FALSE）                                          
inti 									由所在平台决定其精度的整数（一般为int32或int64）                                 
int8 									整数，范围为?128至127                                                            
int16 								整数，范围为?32 768至32 767                                                     
int32 								整数，范围为?231至231 ?1                                                        
int64 								整数，范围为?263至263 ?1                                                        
uint8 								无符号整数，范围为0至255                                                        
uint16 							  无符号整数，范围为0至65 535                                                    
uint32 							  无符号整数，范围为0至232?1                                                     
uint64 							  无符号整数，范围为0至264?1                                                     
float16							  半精度浮点数（16位）：其中用1位表示正负号， 5位表示指数， 10位表示尾数        
float32							  单精度浮点数（32位）：其中用1位表示正负号， 8位表示指数， 23位表示尾数        
float64或float			   双精度浮点数（64位）：其中用1位表示正负号， 11位表示指数， 52位表示尾数
complex64 					  复数，分别用两个32位浮点数表示实部和虚部                                    
complex128或complex   复数，分别用两个64位浮点数表示实部和虚部                          

In [7]:
np.float64(2)
np.bool(3)

2.0

True

In [8]:
# np.uint8(9999999999999) #OverflowError: Python int too large to convert to C long

在NumPy中，许多函数的参数中可以指定数据类型，通常这个参数是可选的：

In [9]:
np.arange(7, dtype=np.uint8)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint8)

### 2.2.3数据类型对象

数据类型对象是numpy.dtype类的实例。如前所述， NumPy数组是有数据类型的，更确切
地说， NumPy数组中的每一个元素均为相同的数据类型。数据类型对象可以给出单个数组元素在
内存中占用的字节数，即dtype类的itemsize属性：

In [10]:
np.arange(7).dtype.itemsize
np.arange(7, dtype=np.uint8).dtype.itemsize

4

1

### 2.2.4字符编码

NumPy可以使用字符编码来表示数据类型，这是为了兼容NumPy的前身Numeric。我不推荐
使用字符编码，但有时会用到，因此下面还是列出了字符编码的对应表。读者应该优先使用dtype
对象来表示数据类型，而不是这些字符编码。


整数 i
无符号整数 u
单精度浮点数 f
双精度浮点数 d
布尔值 b
复数 D
字符串 S
unicode字符串 U
void （空） V

In [11]:
np.arange(7)
np.arange(7, dtype=np.uint8)
np.arange(7,dtype='f')
np.arange(7,dtype='D')

array([0, 1, 2, 3, 4, 5, 6])

array([0, 1, 2, 3, 4, 5, 6], dtype=uint8)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.], dtype=float32)

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j])

### 2.2.5自定义数据类型

完整的NumPy数据类型列表

In [12]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint32,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 9: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 10: numpy.uint64,
 'long': numpy.int32,
 'l': numpy.int32,
 7: numpy.int32,
 'L': numpy.uint32,
 8: numpy.uint32,
 'longlong': numpy.int64,
 'q': numpy.int64,
 'ulonglong': numpy.uint64,
 'Q': numpy.uint64,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float64,
 'g': numpy.float64,
 13: numpy.float64,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14: numpy.complex64,
 'c

### 2.2.6 dtype类的属性

不建议使用

In [13]:
t=np.dtype('Float64')
t.char
t.type
t.str

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  """Entry point for launching an IPython kernel.


'd'

numpy.float64

'<f8'

## 2.3创建自定义数据类型

不建议使用

In [14]:
# t = np.dtype([(,name', str_, 40), ('numitems', int32), ('price',float32)])
#我们创建了一种自定义的异构数据类型，该数据类型包括一个用字符串记录的名字、一个用整数记录的数字以及一个用浮点数记录的价格

## 2.4 一维数组的索引和切片

In [15]:
a = np.arange(6)
a[2:5]

array([2, 3, 4])

In [16]:
a[-4:-1]

array([2, 3, 4])

In [17]:
a[::-1]

array([5, 4, 3, 2, 1, 0])

In [18]:
a[::2]

array([0, 2, 4])

## 2.5 动手实践：多维数组的切片和索引

ndarray支持在多维数组上的切片操作。为了方便起见，我们可以用一个省略号（...）来
表示遍历剩下的维度。

In [19]:
a=np.arange(24).reshape(2,3,4)
a
a.shape

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(2, 3, 4)

### 多维数组的切片操作

In [20]:
a
a[0,0,:]
a[0,:,0]
a[:,0,0]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([0, 1, 2, 3])

array([0, 4, 8])

array([ 0, 12])

In [21]:
a
a[0,:,:]
a[:,0,:]
a[:,:,0]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

array([[ 0,  4,  8],
       [12, 16, 20]])

如果要选取第1层楼的最后一列的所有房间，使用如下代码：

In [22]:
a
a[:,:,-1]
a[0,:,-1]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[ 3,  7, 11],
       [15, 19, 23]])

array([ 3,  7, 11])

如果在多维数组中执行翻转一维数组的命令，将在最前面的维度上翻转元素的顺序，在我们
的例子中将把第1层楼和第2层楼的房间交换

In [23]:
a
a[::-1]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

## 2.6 动手实践：改变数组的维度

(1) ravel 我们可以用ravel函数完成展平的操作

In [24]:
a
a.ravel()   #<class 'numpy.ndarray'>

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

(2) flatten 这个函数恰如其名， flatten就是展平的意思，与ravel函数的功能相同。
不过，flatten函数会请求分配内存来保存结果，而ravel函数只是返回数组的一个视图（view）

In [25]:
a
a.flatten()   #<class 'numpy.ndarray'>

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

(3) 用元组设置维度 除了可以使用reshape函数，我们也可以直接用一个正整数元组来设
置数组的维度，如下所示

In [26]:
a
a.shape=(4,6)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

(4) transpose 在线性代数中， 转置矩阵是很常见的操作。对于多维数组，我们也可以这样做：

In [27]:
a
a.transpose()
a.T

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

(5) resize resize和reshape函数的功能一样，但resize会直接修改所操作的数组：

In [28]:
a
a.resize(2,12)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [29]:
a=np.array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])
a.shape=(1,-1)
a
a.transpose()
a
a.T
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]])

## 2.7 数组的组合

NumPy数组有水平组合、垂直组合和深度组合等多种组合方式，我们将使用vstack、
dstack、 hstack、 column_stack、 row_stack以及concatenate函数来完成数组的组合。

In [30]:
a=np.arange(9).reshape(3,3)
a
b=2*a
b
(a,b)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

(1) 水平组合 我们先从水平组合开始练习。将ndarray对象构成的元组作为参数，传给
hstack函数。如下所示：

In [31]:
(a,b)
np.hstack((a,b))
np.concatenate((a,b),axis=1)

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

(2) 垂直组合 垂直组合同样需要构造一个元组作为参数，只不过这次的函数变成了
vstack。如下所示：

In [32]:
(a,b)
np.vstack((a,b))

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

(3) 深度组合 将相同的元组作为参数传给dstack函数，即可完成数组的深度组合。

In [33]:
(a,b)
np.dstack((a,b))
np.dstack((a,b)).shape
#对比 hstack
np.hstack((a,b))

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

(3, 3, 2)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

(4) 列组合 column_stack函数对于一维数组将按列方向进行组合

对于二维数组，列组合是等效于hstack 效果一样

In [34]:
(a,b)
np.column_stack((a,b))
np.column_stack((a,b)) ==np.hstack((a,b))

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]), array([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]]))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

对于多维数组也是一样

In [35]:
a3=np.arange(24).reshape(2,3,4)
a3
b3=2*a3
b3
np.hstack((a3,b3)) == np.column_stack((a3,b3))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]])

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]], dtype=bool)

(5) 行组合 当然， NumPy中也有按行方向进行组合的函数，它就是row_stack。对于两
个一维数组，将直接层叠起来组合成一个二维数组，等价于 vstack()

## 2.9 数组的分割

NumPy数组可以进行水平、垂直或深度分割，相关的函数有hsplit、 vsplit、 dsplit和
split。我们可以将数组分割成相同大小的子数组，也可以指定原数组中需要分割的位置。

(1) 水平分割 下面的代码将把数组沿着水平方向分割为3个相同大小的子数组，从水平方向平移向垂直方向切

In [36]:
a
np.hsplit(a,3)
np.split(a,3,axis=1)
len(np.hsplit(a,3))
np.hsplit(a,3)[0].shape

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

3

(3, 1)

(2) 垂直分割 vsplit函数将把数组沿着垂直方向分割：从垂直方向平移向水平方向切

In [37]:
a
np.vsplit(a,3)
np.split(a,3,axis=0)
len(np.vsplit(a,3))
np.vsplit(a,3)[0].shape

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

3

(1, 3)

(3) 深度分割 不出所料， dsplit函数将按深度方向分割数组。

In [38]:
a3
a3.shape
b3
c3=np.dstack((a3,b3))
c3
d3=np.dsplit(c3,a3.shape[0])
d3
a3==d3[0]
b3==d3[1]


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(2, 3, 4)

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[24, 26, 28, 30],
        [32, 34, 36, 38],
        [40, 42, 44, 46]]])

array([[[ 0,  1,  2,  3,  0,  2,  4,  6],
        [ 4,  5,  6,  7,  8, 10, 12, 14],
        [ 8,  9, 10, 11, 16, 18, 20, 22]],

       [[12, 13, 14, 15, 24, 26, 28, 30],
        [16, 17, 18, 19, 32, 34, 36, 38],
        [20, 21, 22, 23, 40, 42, 44, 46]]])

[array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]), array([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],
 
        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]])]

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]], dtype=bool)

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]], dtype=bool)

## 2.11 数组的属性

In [39]:
a3
a3.shape

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

(2, 3, 4)

ndim属性，给出数组的维数，或数组轴的个数：

In [40]:
a3.ndim

3

size属性，给出数组元素的总个数，如下所示：

In [41]:
a3.size

24

itemsize属性，给出数组中的元素在内存中所占的字节数

In [42]:
a3.itemsize

4

如果你想知道整个数组所占的存储空间，可以用nbytes属性来查看。这个属性的值其实
就是itemsize和size属性值的乘积

In [43]:
a3.nbytes
a3.nbytes == a3.size * a3.itemsize 

96

True

T属性的效果和transpose函数一样

In [44]:
a3
a3.T
a3.T.shape

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

(4, 3, 2)

在NumPy中，复数的虚部是用j表示的。例如，我们可以创建一个由复数构成的数组

In [45]:
np.array([1,2+1.j,3.j + 1])

array([ 1.+0.j,  2.+1.j,  1.+3.j])

real属性，给出复数数组的实部。如果数组中只包含实数元素，则其real属性将输出原
数组

In [46]:
np.array([1,2+1.j,3.j + 1]).real

array([ 1.,  2.,  1.])

imag属性，给出复数数组的虚部

In [47]:
np.array([1,2+1.j,3.j + 1]).imag

array([ 0.,  1.,  3.])

如果数组中包含复数元素，则其数据类型自动变为复数型：

In [48]:
np.array([1,2+1.j,3.j + 1]).dtype
np.array([1,2+1.j,3.j + 1]).dtype.str
a.dtype
a.dtype.str

dtype('complex128')

'<c16'

dtype('int32')

'<i4'

flat属性将返回一个numpy.flatiter对象， 这是获得flatiter对象的唯一方式——我
们无法访问flatiter的构造函数。这个所谓的“扁平迭代器”可以让我们像遍历一维数
组一样去遍历任意的多维数组

In [49]:
a3
a3.flat
for x in a3.flat:
    x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

0

1

2

3

4

5

6

7

8

9

10

11

12

13

14

15

16

17

18

19

20

21

22

23

我们还可以用flatiter对象直接获取一个数组元素

In [50]:
a3.flat[10]
a3.flat[1:10]

10

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

flat属性是一个可赋值的属性。对flat属性赋值将导致整个数组的元素都被覆盖：

In [51]:
tempa=a3.copy()
tempa.flat = 0
tempa
a3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

## 2.12 动手实践：数组的转换

(1) 我们可以使用tolist函数将NumPy数组转换成Python列表。

In [52]:
a3
a3.tolist()

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

[[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]],
 [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]]]

(2) astype函数可以在转换数组时指定数据类型：

In [53]:
a3.astype(str)
a3.astype(float)

array([[['0', '1', '2', '3'],
        ['4', '5', '6', '7'],
        ['8', '9', '10', '11']],

       [['12', '13', '14', '15'],
        ['16', '17', '18', '19'],
        ['20', '21', '22', '23']]], 
      dtype='<U11')

array([[[  0.,   1.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]],

       [[ 12.,  13.,  14.,  15.],
        [ 16.,  17.,  18.,  19.],
        [ 20.,  21.,  22.,  23.]]])

## 2.13 本章小结

在本章中，我们学习了很多NumPy的基础知识：数据类型和NumPy数组。对于数组而言，
有很多属性可以用来描述数组，数据类型就是其中之一。在NumPy中，数组的数据类型是用对象
来完善表示的。
类似于Python列表， NumPy数组也可以方便地进行切片和索引操作。在多维数组上， NumPy
有明显的优势。
涉及改变数组维度的操作有很多种——组合、调整、设置维度和分割等。在这一章中，对很
多改变数组维度的实用函数进行了说明。这样的处理。
在学习完基础知识后，我们将进入到第3章来学习NumPy中的常用函数，包括基本数学函数
和统计函数等。